// src/config/category.js
export const CAMPUS_OPTIONS = [
  { value: '', label: 'All Campuses' },
  { value: 'UG', label: 'Univ. of Ghana' },
  { value: 'KNUST', label: 'KNUST' },
  { value: 'UCC', label: 'UCC' },
  { value: 'UEW', label: 'UEW' },
  { value: 'UPSA', label: 'UPSA' },
  { value: 'GIMPA', label: 'GIMPA' },
  { value: 'ASHESI', label: 'Ashesi' },
  { value: 'ATU', label: 'ATU' },
  { value: 'OTHER', label: 'Other' },
];

export const SUBCATEGORY_MAP = {
  'electronics': [
    { value: 'headphones-earbuds', label: 'Headphones & Earbuds' },
    { value: 'speakers', label: 'Speakers' },
    { value: 'chargers-cables', label: 'Chargers & Cables' },
    { value: 'power-banks', label: 'Power Banks' },
    { value: 'smartwatches', label: 'Smartwatches' },
    { value: 'cameras', label: 'Cameras' },
    { value: 'other-electronics', label: 'Other' },
  ],
  'phones and tablets': [
    { value: 'smartphones', label: 'Smartphones' },
    { value: 'tablets', label: 'Tablets' },
    { value: 'ipads', label: 'iPads' },
    { value: 'phone-cases', label: 'Phone Cases' },
    { value: 'screen-protectors', label: 'Screen Protectors' },
    { value: 'other-phone-accessories', label: 'Other' },
  ],
  'computers and laptops': [
    { value: 'laptops', label: 'Laptops' },
    { value: 'desktops', label: 'Desktops' },
    { value: 'monitors', label: 'Monitors' },
    { value: 'keyboards', label: 'Keyboards' },
    { value: 'mouse', label: 'Mouse' },
    { value: 'laptop-bags', label: 'Laptop Bags' },
    { value: 'software', label: 'Software' },
    { value: 'other-computer-accessories', label: 'Other' },
  ],
  'gaming': [
    { value: 'consoles', label: 'Consoles' },
    { value: 'games', label: 'Games' },
    { value: 'controllers', label: 'Controllers' },
    { value: 'gaming-accessories', label: 'Accessories' },
  ],
  'fashion': [
    { value: 'men-clothing', label: "Men's Clothing" },
    { value: 'women-clothing', label: "Women's Clothing" },
    { value: 'unisex-clothing', label: 'Unisex' },
    { value: 'shoes', label: 'Shoes' },
    { value: 'bags', label: 'Bags' },
    { value: 'watches', label: 'Watches' },
    { value: 'jewelry', label: 'Jewelry' },
    { value: 'other-fashion', label: 'Other' },
  ],
  'books-course-materials': [
    { value: 'textbooks', label: 'Textbooks' },
    { value: 'course-notes', label: 'Course Notes' },
    { value: 'past-questions', label: 'Past Questions' },
    { value: 'stationery', label: 'Stationery' },
    { value: 'novels', label: 'Novels' },
    { value: 'other-books', label: 'Other' },
  ],
  'hostel-items': [
    { value: 'bedding', label: 'Bedding' },
    { value: 'kitchenware', label: 'Kitchenware' },
    { value: 'cleaning-supplies', label: 'Cleaning' },
    { value: 'storage', label: 'Storage' },
    { value: 'lighting', label: 'Lighting' },
    { value: 'other-hostel', label: 'Other' },
  ],
  'appliances': [
    { value: 'fans', label: 'Fans' },
    { value: 'irons', label: 'Irons' },
    { value: 'kettles', label: 'Kettles' },
    { value: 'blenders', label: 'Blenders' },
    { value: 'microwaves', label: 'Microwaves' },
    { value: 'other-appliances', label: 'Other' },
  ],
  'furniture': [
    { value: 'chairs', label: 'Chairs' },
    { value: 'tables-desks', label: 'Tables & Desks' },
    { value: 'beds-mattresses', label: 'Beds & Mattresses' },
    { value: 'shelves', label: 'Shelves' },
    { value: 'other-furniture', label: 'Other' },
  ],
  'beauty and grooming': [
    { value: 'skincare', label: 'Skincare' },
    { value: 'makeup', label: 'Makeup' },
    { value: 'hair-care', label: 'Hair Care' },
    { value: 'perfumes', label: 'Perfumes' },
    { value: 'nail-care', label: 'Nail Care' },
    { value: 'other-beauty', label: 'Other' },
  ],
  'sports and fitness': [
    { value: 'sports-equipment', label: 'Equipment' },
    { value: 'gym-gear', label: 'Gym Gear' },
    { value: 'activewear', label: 'Activewear' },
    { value: 'other-sports', label: 'Other' },
  ],
  'food and drinks': [
    { value: 'snacks', label: 'Snacks' },
    { value: 'drinks', label: 'Drinks' },
    { value: 'homemade-meals', label: 'Homemade Meals' },
    { value: 'baked-goods', label: 'Baked Goods' },
    { value: 'other-food', label: 'Other' },
  ],
  'services': [
    { value: 'tutoring', label: 'Tutoring' },
    { value: 'graphic-design', label: 'Graphic Design' },
    { value: 'photography', label: 'Photography' },
    { value: 'printing-photocopy', label: 'Printing' },
    { value: 'laundry', label: 'Laundry' },
    { value: 'barbering-hairdressing', label: 'Barbering/Hair' },
    { value: 'tech-repairs', label: 'Tech Repairs' },
    { value: 'other-services', label: 'Other' },
  ],
};

export const SORT_OPTIONS = [
  { id: 'newest', label: 'Newest First', icon: '🕐' },
  { id: 'price-asc', label: 'Price: Low to High', icon: '⬆️' },
  { id: 'price-desc', label: 'Price: High to Low', icon: '⬇️' },
  { id: 'popular', label: 'Most Viewed', icon: '📈' },
];

export const CONDITION_CONFIG = {
  'new': { label: 'New', color: '#2E7D32', bg: '#E8F5E9' },
  'like-new': { label: 'Like New', color: '#2E7D32', bg: '#E8F5E9' },
  'excellent': { label: 'Excellent', color: '#1565C0', bg: '#E3F2FD' },
  'good': { label: 'Good', color: '#F57F17', bg: '#FFF8E1' },
  'fair': { label: 'Fair', color: '#E65100', bg: '#FFF3E0' },
  'slightly-used': { label: 'Slightly Used', color: '#E65100', bg: '#FFF3E0' },
  'for-parts': { label: 'For Parts', color: '#C62828', bg: '#FFEBEE' },
};