// src/config/cedimart.js
export const CATEGORY_CONFIG = {
  electronics: { icon: '🔌', label: 'Electronics', color: '#E3F2FD', accent: '#1565C0' },
  'phones and tablets': { icon: '📱', label: 'Phones & Tablets', color: '#F3E5F5', accent: '#6A1B9A' },
  'computers and laptops': { icon: '💻', label: 'Computers & Laptops', color: '#E8EAF6', accent: '#283593' },
  gaming: { icon: '🎮', label: 'Gaming', color: '#FCE4EC', accent: '#880E4F' },
  fashion: { icon: '👗', label: 'Fashion', color: '#FFF3E0', accent: '#E65100' },
  'books-course-materials': { icon: '📚', label: 'Books', color: '#FFF9C4', accent: '#F57F17' },
  'hostel-items': { icon: '🛏️', label: 'Hostel Items', color: '#E8F5E9', accent: '#2E7D32' },
  appliances: { icon: '🔧', label: 'Appliances', color: '#EFEBE9', accent: '#4E342E' },
  furniture: { icon: '🪑', label: 'Furniture', color: '#F1F8E9', accent: '#33691E' },
  'beauty and grooming': { icon: '💄', label: 'Beauty', color: '#FCE4EC', accent: '#AD1457' },
  'sports and fitness': { icon: '⚽', label: 'Sports', color: '#E8F5E9', accent: '#1B5E20' },
  accessories: { icon: '👜', label: 'Accessories', color: '#FFF9C4', accent: '#827717' },
  'food and drinks': { icon: '🍱', label: 'Food', color: '#FBE9E7', accent: '#BF360C' },
  services: { icon: '🛠️', label: 'Services', color: '#E3F2FD', accent: '#01579B' },
  other: { icon: '📦', label: 'Other', color: '#F5F5F5', accent: '#616161' },
};

export const CONDITION_LABELS = {
  'new': { label: 'Brand New', color: '#1B5E20', bg: '#E8F5E9' },
  'like-new': { label: 'Like New', color: '#1565C0', bg: '#E3F2FD' },
  'excellent': { label: 'Excellent', color: '#4527A0', bg: '#EDE7F6' },
  'good': { label: 'Good', color: '#E65100', bg: '#FFF3E0' },
  'fair': { label: 'Fair', color: '#827717', bg: '#F9FBE7' },
  'slightly-used': { label: 'Slight Used', color: '#4E342E', bg: '#EFEBE9' },
  'for-parts': { label: 'For Parts', color: '#B71C1C', bg: '#FFEBEE' },
};

export const HERO_SLIDES = [
  {
    id: '1',
    image: 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780782982/flyer13_1_fyp0xj.png',
    tag: '🎓 Campus Marketplace',
    title: 'Buy & Sell on Campus',
    subtitle: "Connect with students across Ghana's top universities",
    btnText: 'Start Shopping',
    accentColor: '#fff',
    overlayColor: 'rgba(0,0,0,0.45)',
    nav: { path: '/products' },
  },
  {
    id: '2',
    image: 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780771354/flyer11_qkxwpv.jpg',
    tag: '💻 Electronics & Gadgets',
    title: 'Laptops, Phones & More',
    subtitle: 'Student-priced tech from trusted campus sellers',
    btnText: 'Browse Electronics',
    accentColor: '#90CAF9',
    overlayColor: 'rgba(10,20,60,0.50)',
    nav: { path: '/products', params: '?category=electronics' },
  },
  {
    id: '3',
    image: 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1781101245/fashion_banner_ibwmaz.png',
    tag: '👗 Fashion & Style',
    title: 'Upgrade Your Wardrobe',
    subtitle: 'Trendy outfits, accessories & vintage finds at great prices',
    btnText: 'Shop Fashion',
    accentColor: '#FFCC80',
    overlayColor: 'rgba(60,30,0,0.46)',
    nav: { path: '/products', params: '?category=fashion' },
  },
  {
    id: '4',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    tag: '🛏️ Hostel Essentials',
    title: 'Furnish Your Hostel Room',
    subtitle: 'Beds, fans, fridges and everything you need',
    btnText: 'Explore Hostel Items',
    accentColor: '#A5D6A7',
    overlayColor: 'rgba(0,30,10,0.46)',
    nav: { path: '/products', params: '?category=hostel-items' },
  },
];