// src/config/products.js
export const CATEGORIES = [
  { id: 'all', label: 'All', emoji: '🛍️', color: '#E8F5E9', accent: '#2E7D32' },
  { id: 'electronics', label: 'Electronics', emoji: '🔌', color: '#E3F2FD', accent: '#1565C0' },
  { id: 'phones and tablets', label: 'Phones & Tablets', emoji: '📱', color: '#F3E5F5', accent: '#6A1B9A' },
  { id: 'computers and laptops', label: 'Computers & Laptops', emoji: '💻', color: '#E8EAF6', accent: '#283593' },
  { id: 'gaming', label: 'Gaming', emoji: '🎮', color: '#FCE4EC', accent: '#880E4F' },
  { id: 'fashion', label: 'Fashion', emoji: '👗', color: '#FFF3E0', accent: '#E65100' },
  { id: 'books-course-materials', label: 'Books & Notes', emoji: '📚', color: '#FFF9C4', accent: '#F57F17' },
  { id: 'hostel-items', label: 'Hostel Items', emoji: '🛏️', color: '#E8F5E9', accent: '#2E7D32' },
  { id: 'appliances', label: 'Appliances', emoji: '🔧', color: '#EFEBE9', accent: '#4E342E' },
  { id: 'furniture', label: 'Furniture', emoji: '🪑', color: '#F1F8E9', accent: '#33691E' },
  { id: 'beauty and grooming', label: 'Beauty & Grooming', emoji: '💄', color: '#FCE4EC', accent: '#AD1457' },
  { id: 'sports and fitness', label: 'Sports & Fitness', emoji: '⚽', color: '#E8F5E9', accent: '#1B5E20' },
  { id: 'accessories', label: 'Accessories', emoji: '👜', color: '#FFF9C4', accent: '#827717' },
  { id: 'food and drinks', label: 'Food & Drinks', emoji: '🍱', color: '#FBE9E7', accent: '#BF360C' },
  { id: 'services', label: 'Services', emoji: '🛠️', color: '#E3F2FD', accent: '#01579B' },
  { id: 'other', label: 'Other', emoji: '📦', color: '#F5F5F5', accent: '#616161' },
];

export const SUBCATEGORIES = {
  'electronics': [
    { id: 'headphones-earbuds', label: 'Headphones & Earbuds' },
    { id: 'speakers', label: 'Speakers' },
    { id: 'chargers-cables', label: 'Chargers & Cables' },
    { id: 'power-banks', label: 'Power Banks' },
    { id: 'smartwatches', label: 'Smartwatches' },
    { id: 'cameras', label: 'Cameras' },
    { id: 'other-electronics', label: 'Other Electronics' },
  ],
  'phones and tablets': [
    { id: 'smartphones', label: 'Smartphones' },
    { id: 'tablets', label: 'Tablets' },
    { id: 'ipads', label: 'iPads' },
    { id: 'phone-cases', label: 'Phone Cases' },
    { id: 'screen-protectors', label: 'Screen Protectors' },
    { id: 'other-phone-accessories', label: 'Other Accessories' },
  ],
  'computers and laptops': [
    { id: 'laptops', label: 'Laptops' },
    { id: 'desktops', label: 'Desktops' },
    { id: 'monitors', label: 'Monitors' },
    { id: 'keyboards', label: 'Keyboards' },
    { id: 'mouse', label: 'Mouse' },
    { id: 'laptop-bags', label: 'Laptop Bags' },
    { id: 'software', label: 'Software' },
    { id: 'other-computer-accessories', label: 'Other' },
  ],
  'gaming': [
    { id: 'consoles', label: 'Consoles' },
    { id: 'games', label: 'Games' },
    { id: 'controllers', label: 'Controllers' },
    { id: 'gaming-accessories', label: 'Accessories' },
  ],
  'fashion': [
    { id: 'men-clothing', label: "Men's Clothing" },
    { id: 'women-clothing', label: "Women's Clothing" },
    { id: 'unisex-clothing', label: 'Unisex Clothing' },
    { id: 'shoes', label: 'Shoes' },
    { id: 'bags', label: 'Bags' },
    { id: 'watches', label: 'Watches' },
    { id: 'jewelry', label: 'Jewelry' },
    { id: 'other-fashion', label: 'Other Fashion' },
  ],
  'books-course-materials': [
    { id: 'textbooks', label: 'Textbooks' },
    { id: 'course-notes', label: 'Course Notes' },
    { id: 'past-questions', label: 'Past Questions' },
    { id: 'stationery', label: 'Stationery' },
    { id: 'novels', label: 'Novels' },
    { id: 'other-books', label: 'Other Books' },
  ],
  'hostel-items': [
    { id: 'bedding', label: 'Bedding' },
    { id: 'kitchenware', label: 'Kitchenware' },
    { id: 'cleaning-supplies', label: 'Cleaning Supplies' },
    { id: 'storage', label: 'Storage' },
    { id: 'lighting', label: 'Lighting' },
    { id: 'other-hostel', label: 'Other' },
  ],
  'appliances': [
    { id: 'fans', label: 'Fans' },
    { id: 'heaters', label: 'Heaters' },
    { id: 'irons', label: 'Irons' },
    { id: 'kettles', label: 'Kettles' },
    { id: 'blenders', label: 'Blenders' },
    { id: 'microwaves', label: 'Microwaves' },
    { id: 'other-appliances', label: 'Other' },
  ],
  'furniture': [
    { id: 'chairs', label: 'Chairs' },
    { id: 'tables-desks', label: 'Tables & Desks' },
    { id: 'beds-mattresses', label: 'Beds & Mattresses' },
    { id: 'shelves', label: 'Shelves' },
    { id: 'other-furniture', label: 'Other' },
  ],
  'beauty and grooming': [
    { id: 'skincare', label: 'Skincare' },
    { id: 'makeup', label: 'Makeup' },
    { id: 'hair-care', label: 'Hair Care' },
    { id: 'perfumes', label: 'Perfumes' },
    { id: 'nail-care', label: 'Nail Care' },
    { id: 'other-beauty', label: 'Other' },
  ],
  'sports and fitness': [
    { id: 'sports-equipment', label: 'Sports Equipment' },
    { id: 'gym-gear', label: 'Gym Gear' },
    { id: 'activewear', label: 'Activewear' },
    { id: 'other-sports', label: 'Other' },
  ],
  'accessories': [
    { id: 'phone-accessories', label: 'Phone Accessories' },
    { id: 'laptop-accessories', label: 'Laptop Accessories' },
    { id: 'fashion-accessories', label: 'Fashion Accessories' },
    { id: 'other-accessories', label: 'Other' },
  ],
  'food and drinks': [
    { id: 'snacks', label: 'Snacks' },
    { id: 'drinks', label: 'Drinks' },
    { id: 'homemade-meals', label: 'Homemade Meals' },
    { id: 'baked-goods', label: 'Baked Goods' },
    { id: 'other-food', label: 'Other Food' },
  ],
  'services': [
    { id: 'tutoring', label: 'Tutoring' },
    { id: 'graphic-design', label: 'Graphic Design' },
    { id: 'photography', label: 'Photography' },
    { id: 'printing-photocopy', label: 'Printing & Photocopy' },
    { id: 'laundry', label: 'Laundry' },
    { id: 'barbering-hairdressing', label: 'Barbing & Hairdressing' },
    { id: 'tech-repairs', label: 'Tech Repairs' },
    { id: 'other-services', label: 'Other Services' },
  ],
  'other': [
    { id: 'miscellaneous', label: 'Miscellaneous' },
  ],
};

export const CONDITION_CONFIG = {
  'new': { label: 'Brand New', textColor: '#1B5E20', bg: '#E8F5E9' },
  'like-new': { label: 'Like New', textColor: '#1565C0', bg: '#E3F2FD' },
  'excellent': { label: 'Excellent', textColor: '#4527A0', bg: '#EDE7F6' },
  'good': { label: 'Good', textColor: '#E65100', bg: '#FFF3E0' },
  'fair': { label: 'Fair', textColor: '#827717', bg: '#F9FBE7' },
  'slightly-used': { label: 'Slight Used', textColor: '#4E342E', bg: '#EFEBE9' },
  'for-parts': { label: 'For Parts', textColor: '#B71C1C', bg: '#FFEBEE' },
};

export const SORT_OPTIONS = [
  { id: 'newest', label: 'Newest First', icon: '🕐' },
  { id: 'oldest', label: 'Oldest First', icon: '⏳' },
  { id: 'price-asc', label: 'Price: Low → High', icon: '⬆️' },
  { id: 'price-desc', label: 'Price: High → Low', icon: '⬇️' },
  { id: 'popular', label: 'Most Popular', icon: '📈' },
  { id: 'rating', label: 'Top Rated', icon: '⭐' },
];

export const CAMPUS_OPTIONS = [
  { id: '', label: 'All Campuses' },
  { id: 'UG', label: 'University of Ghana' },
  { id: 'KNUST', label: 'KNUST' },
  { id: 'UCC', label: 'Univ. of Cape Coast' },
  { id: 'ASHESI', label: 'Ashesi University' },
  { id: 'GIMPA', label: 'GIMPA' },
  { id: 'UEW', label: 'Univ. of Education' },
  { id: 'UPSA', label: 'UPSA' },
  { id: 'ATU', label: 'Accra Technical Univ.' },
  { id: 'OTHER', label: 'Other Campus' },
];

export const HERO_IMAGES = {
  all: 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780694282/campus_ecommerce_flyer_1_jqpppo.jpg',
  electronics: 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780694855/computers_flyer_ceekpj.jpg',
  'phones and tablets': 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780694855/computers_flyer_ceekpj.jpg',
  'computers and laptops': 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780694855/computers_flyer_ceekpj.jpg',
  gaming: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800',
  fashion: 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1781101245/fashion_banner_ibwmaz.png',
  'books-course-materials': 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780695851/books_flyer_ljnqis.jpg',
  'hostel-items': 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
  appliances: 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780690124/appliances_bkv5s1.jpg',
  furniture: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
  'beauty and grooming': 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780690851/beauty_m4uwn1.jpg',
  'sports and fitness': 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780690851/sports_and_fitness_g3ozaa.webp',
  accessories: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
  'food and drinks': 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780690853/food_and_drinks_knhmgb.jpg',
  services: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800',
  other: 'https://res.cloudinary.com/duv3qvvjz/image/upload/v1780694282/campus_ecommerce_flyer_1_jqpppo.jpg',
};